[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
tide = "0.16.0"
uuid = "1.3.0"
bonsaidb = {git = "https://github.com/khonsulabs/bonsaidb", features = ["local"]}
bonsaidb-core = {git = "https://github.com/khonsulabs/bonsaidb", features = ["uuid"]}
bonsaidb-local = {git = "https://github.com/khonsulabs/bonsaidb"}
bcrypt = "0.14.0"


